# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tuding' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tuding
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  target 'tudingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tuding-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tuding-tvOS

  target 'tuding-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
